version: '3.8'

services:
  litellm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: litellm-bedrock
    ports:
      - "4002:4002"
    env_file:
      - .env
    environment:
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - LITELLM_LOG=DEBUG  # Use new logging method (replaces set_verbose)
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./logs:/app/logs
      - ~/.aws:/root/.aws:ro  # Mount AWS credentials from local machine
    restart: unless-stopped
    networks:
      - litellm-network
      - docker_stetai-network  # Connect to Langfuse network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  litellm-network:
    name: litellm-network
    driver: bridge
  docker_stetai-network:
    external: true  # Use existing Langfuse network

volumes:
  logs:

